In [ ]:
!pip install scikit-learn

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

In [23]:

df = pd.read_csv('IMDB Dataset.csv')

In [24]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [25]:
df.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [26]:
df.isnull()

       review  sentiment
0       False      False
1       False      False
2       False      False
3       False      False
4       False      False
...       ...        ...
49995   False      False
49996   False      False
49997   False      False
49998   False      False
49999   False      False

[50000 rows x 2 columns]

In [27]:

df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})


X_train, X_test, y_train, y_test = train_test_split(
    df['review'], df['sentiment'], test_size=0.2, random_state=42
)

In [28]:

tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)


model = LogisticRegression()
model.fit(X_train_tfidf, y_train)


y_pred = model.predict(X_test_tfidf)

In [29]:
# Create a test sentence
test_review = ["This movie was a total worth of time, I love it."]

# Step 1: Convert text to numbers (Outcome starts here)
test_vector = tfidf.transform(test_review)

# Step 2: The Model makes a decision (The Prediction Outcome)
result = model.predict(test_vector)

# Step 3: Print the result
print("Positive" if result[0] == 1 else "Negative")

Positive

In [30]:
print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall:    {recall_score(y_test, y_pred):.4f}")

Accuracy:  0.8889
Precision: 0.8783
Recall:    0.9049